apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-api-python-app
  labels:
    app: flask-api-python-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: flask-api-python-app
  template:
    metadata:
      labels:
        app: flask-api-python-app
    spec:
      containers:
        - name: flask-api-python-app
          image: akshayreddy597/flask-api:v1
          ports:
            - containerPort: 5000  
